#!/bin/bash
# G1' cocotb suites of src/riscq/ddr/cocotb (writer, cbuf_poller, mmu2, smoke) on the RTL generated by
# `mill-1.1.0 runMain riscq.ddr.sim.GenUplinkUnits` (build/uplink-units).
#   run-cocotb.sh [tag]            -> $GATE_LOG_DIR/<tag>_cocotb_*.log and <tag>_cocotb_summary.tsv
# Exit 0 only if every seed of every suite exits 0 and its TESTS= line shows FAIL=0 (P3b re-audit item 2).
# The Verilator build (sim_build) is kept between runs (item 5): each Makefile lists VERILOG_SOURCES before cocotb's
# Makefile.sim, so a changed RTL re-runs Verilator, which rewrites only the C++ whose content changed; an unchanged
# RTL reuses the build. COCOTB_CLEAN=1 forces fresh builds. SEEDS (default "20260823 1 424242"); smoke runs one seed.
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
tag=${1:-g1}
gate_need make cocotb-config verilator
[ -f "$GATE_REPO/build/uplink-units/mmu2.v" ] || gate_die "no build/uplink-units RTL: run mill-1.1.0 runMain riscq.ddr.sim.GenUplinkUnits"
SEEDS="${SEEDS:-20260823 1 424242}"
S=$GATE_LOG_DIR/${tag}_cocotb_summary.tsv; : > "$S"
suite() {
  local s=$1 bad=0 first=1
  cd "$GATE_REPO/src/riscq/ddr/cocotb/$s" || return 1
  rm -f results.xml
  [ "${COCOTB_CLEAN:-0}" = 1 ] && rm -rf sim_build
  for seed in $SEEDS; do
    [ $s = smoke ] && [ $first = 0 ] && continue
    first=0
    local log=$GATE_LOG_DIR/${tag}_cocotb_${s}_${seed}.log t0=$(date +%s.%N)
    gate_run make SEED=$seed > "$log" 2>&1; local rc=$?
    local tl=$(grep -E "TESTS=" "$log" | tail -1 | sed "s/  */ /g")
    local f=$(echo "$tl" | sed -n 's/.*FAIL=\([0-9]*\).*/\1/p') v=PASS
    { [ $rc -ne 0 ] || [ -z "$tl" ] || [ "${f:-x}" != 0 ]; } && { v=FAIL; bad=1; }
    echo -e "$s\tseed=$seed\trc=$rc\t$v\twall=$(printf %.1f $(echo "$(date +%s.%N) - $t0" | bc))s\t$tl" >> "$S"
    rm -f results.xml
  done
  return $bad
}
t0=$(date +%s.%N); pids=()
for s in writer cbuf_poller mmu2 smoke; do suite $s & pids+=($!); done
fail=0; for p in "${pids[@]}"; do wait $p || fail=1; done
echo "ALLDONE fail=$fail wall=$(printf %.1f $(echo "$(date +%s.%N) - $t0" | bc))s" >> "$S"
cat "$S"
exit $fail
