# P3c-2: the uplink's rejected-count Gray counters get ONE set_bus_skew group per counter, written per build into
# <build>/ddr-timing-gray.xdc (XDC has no loops). Sourced by inc/bd-finalize.tcl for antq_uplink builds;
# inc/ddr-check-busskew.tcl checks the coverage on the routed design (one group per counter, the same width for all,
# every Gray bit and first synchronizer flop in its own counter's group, one report_bus_skew row per counter).
# Why per counter, and why 2.0 ns: inc/ddr-timing-bus-skew.md.

# the number of Gray counters in the RTL being packaged: the distinct `reg [W-1:0] dsp_rejGray_<i>;` declarations
# (ReadoutDdrUplink), so the count follows the netlist whatever the config's format (qubit_num or a core list)
proc riscq_gray_counters {rtl} {
  set fh [open $rtl r]; set t [read $fh]; close $fh
  set idx {}
  foreach {_ i} [regexp -all -inline {\mreg\s+\[[0-9]+:0\]\s+dsp_rejGray_([0-9]+)\s*;} $t] { lappend idx $i }
  set idx [lsort -integer -unique $idx]
  for {set k 0} {$k < [llength $idx]} {incr k} {
    if {[lindex $idx $k] != $k} { error "riscq_gray_counters: $rtl declares Gray counters {$idx}, not 0..N-1" }
  }
  return [llength $idx]
}

proc riscq_write_gray_skew {path numCh {bound 2.000}} {
  if {$numCh < 1} { error "riscq_write_gray_skew: numCh $numCh" }
  set fh [open $path w]
  puts $fh "# Generated by inc/ddr-gray-skew.tcl for $numCh rejected-count Gray counters (one bus-skew group per counter)."
  for {set i 0} {$i < $numCh} {incr i} {
    puts $fh "set_bus_skew -from \[get_cells -quiet -hier -filter {NAME =~ */ddrUplink_up/dsp_rejGray_${i}_reg\[*\] && NAME !~ */dsp_rejGray_*_buffercc/*}\] -to \[get_cells -quiet -hier -filter {NAME =~ */ddrUplink_up/dsp_rejGray_${i}_buffercc/buffers_0_reg\[*\]}\] $bound"
  }
  close $fh
  return $path
}
